### ISSUE TITLE
如何安装呢

### ISSUE THREAD

**Issue by cannonli** [aa65535/openwrt-dns-forwarder#1]
是要自己下载编译，打包吗？

有没有类似chinadns一样的ipk文件啊

现在使用shadowsocks+chinadns方案，google、twitter、facebook这种网站打不开，但是gmail访问基本没有问题，在whatismyip.com查询显示的ip地址也是走了shadowsocks代理的

怀疑是dns污染导致的，想尝试一下dns-forwarder方案，但没有看到安装包，是要自己编译吗？

谢谢

**Comment by cc9014** [comment]
在release里面有编译好的安装包。
https://github.com/aa65535/openwrt-dns-forwarder/releases

**Comment by cannonli** [comment]
不好意思，没有看到

谢谢
