### ISSUE TITLE
lede下, dnsforwarder的服务不能启动

### ISSUE THREAD

**Issue by blog2i2j** [aa65535/openwrt-dns-forwarder#12]
我是lede mt7620 17.01, 安装dns-forwarder之后, 重启路由始终无法启动这个服务(已经/etc/init.d/dns-forwarder enable 了), 但手工用/etc/init.d/dns-forwarder restart 可以成功启动.
日志中也找不到蛛丝马迹.

**Comment by aa65535** [comment]
应该是路由器的问题，可以试试将 dns-forwarder 启动优先级调低（数字改大）。

**Comment by jsjhzw** [comment]
我也遇到同样的情况，已经把启动优先级调低99，但是还是不行，必须手动输命令，好在不经常重启的

**Comment by suikatomoki** [comment]
你们不会是把监听地址从0.0.0.0改成127.0.0.1了吧

@aa65535 这种情况下好像真的无法自启

**Comment by aa65535** [comment]
@suikatomoki 无法复现

**Comment by suikatomoki** [comment]
@aa65535 我刚又试了一下 真的自启不了 我也不知道啥原因

**Comment by aa65535** [comment]
可以尝试修改一下端口。

**Comment by suikatomoki** [comment]
@aa65535 不行 修改了还是启动不了 之前系统是op cc的时候也这样，现在我升级成了lede还这样，我没怎么在意这个问题，反正监听0.0.0.0就啥事都没。

**Comment by aa65535** [comment]
可以修改 init script, 添加 log 收集, 然后在启动失败时看一下 `/tmp/dns-forwarder.log` 的内容.
```sh
#!/bin/sh /etc/rc.common
#
# Copyright (C) 2016 Jian Chang <aa65535@live.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=75

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start_instance() {
	local enable
	local listen_addr
	local listen_port
	local dns_servers
	config_get_bool enable $1 enable
	[ "$enable" = 1 ] || return 0
	config_get listen_addr $1 listen_addr
	config_get listen_port $1 listen_port
	config_get dns_servers $1 dns_servers
	/usr/bin/dns-forwarder \
		-b ${listen_addr:-0.0.0.0} \
		-p ${listen_port:-5300} \
		-s ${dns_servers:-8.8.8.8} >/tmp/dns-forwarder.log 2>&1 &
}

start() {
	config_load dns-forwarder
	config_foreach start_instance dns-forwarder
}

stop() {
	killall -9 dns-forwarder
}
```

**Comment by suikatomoki** [comment]
@aa65535 就一条 Can't bind address 127.0.0.1:5300

**Comment by aa65535** [comment]
@suikatomoki 应该是端口被占用了。

**Comment by suikatomoki** [comment]
@aa65535 难以置信 我还试了5303端口 也不行 并且手动start是能启动的 而且 0.0.0.0:5300 能bind成功啊

**Comment by gatoslu** [comment]
会不会是dns-forwarder的luci负责控制的这块在lede中失效，导致在luci中设置dns-forwarder时启动这块没有配置完整

**Comment by wumingsh** [comment]
psg1218 lede (17.01.0, r3205-59508e3) 把地址改成127.0.0.1不能开机自动启动，在shell或者luci里都可以手动启动。

**Comment by nobk** [comment]
我用的也是stable版LEDE Reboot 17.01.0 r3205-59508e3，配置文件如下，开机自启很多次都没问题，所以可能还是你的其他程序导致的冲突。
```
config dns-forwarder
        option enable '1'
        option listen_addr '0.0.0.0'
        option listen_port '5300'
        option dns_servers '8.8.8.8:53'

```

**Comment by wumingsh** [comment]
把 '0.0.0.0' 改成 '127.0.0.1'呢？我用0.0.0.0也能自动启动 @nobk

**Comment by pigpigabc123** [comment]
遇到同样的问题，两种解决方式：
1、在启动脚本中加延时，经测试sleep 15即可解决自启动问题；
2、安装haveged

**Comment by suikatomoki** [comment]
@pigpigabc123  按照方式2 解决了

**Comment by moralrebuild** [comment]
同样的问题发生在我这儿：
TL WR703N, 16M Flash
LEDE 17.01.1
无法自动启动。必须在LuCI中多次手动尝试。端口空闲，鉴于其它程序都可以成功启动绑定端口，应该是dns-forwarder自己的bug

**Comment by Karius** [comment]
同样遇到此问题，只能手动启动

**Comment by Biercenter** [comment]
LEDE 17.01.2一样的问题。问题很奇怪，时好时坏，官方image build自己集成100%无法启动，如果先刷固件，然后使用脚本
`wget http://openwrt-dist.sourceforge.net/auto_install_lede.sh
chmod +x auto_install_lede.sh
./auto_install_lede.sh`
然后通过uci设置也是不行。
最后先刷固件，再通过脚本安装，再用luci页面设置才正常。

**Comment by WordlessEcho** [comment]
问题表现为：
LuCi 无法启动
```/etc/init.d/dns-forwarder start``` 也无法启动，而且日志没有任何有用的输出

只有执行 ```/usr/bin/dns-forwarder start```才能正常启动

**Comment by WordlessEcho** [comment]
尝试修改脚本为上文贴出的脚本后发现运行正常

**Comment by aa65535** [comment]
try [v1.2.1](https://github.com/aa65535/openwrt-dns-forwarder/releases/tag/v1.2.1)

**Comment by WordlessEcho** [comment]
Already fixed in nearly version.
