### ISSUE TITLE
能加入edns-client-subnet吗

### ISSUE THREAD

**Issue by cjjdaq** [aa65535/openwrt-dns-forwarder#16]
能加入edns-client-subnet吗

**Comment by aa65535** [comment]
我在 https://github.com/aa65535/ChinaDNS 里面有加入 ECS ，但是实际上并不好用。

**Comment by cjjdaq** [comment]
可能是8.8.8.8并不保证一定接收ecs client ip
要不你继续完善下chinadns
主从dns（同时支持设置多上游，ecs client ip）
主DNS（国内）：119.29.29.29,119.28.28.28 ecs_ip:自己的公网ip
从DNS（国外）：8.8.8.8,8.8.4.4,vps搭建的dns ecs_ip:自己的ss的ip
hosts列表,匹配直接返回ip
黑白名单： 白名单=dnsmasq_china_list可用+自定义 黑名单=gfwlist可用+自定义
白名单命中直接主dns解析，返回ip
黑名单命中直接从dns解析，返回ip
剩下的：
先向主dns发送请求解析，返回的ip如果匹配chnroute.txt直接返回ip，不匹配直接使用从dns解析，并返回ip（剩下的可能有更好的逻辑）
