### ISSUE TITLE
无线链接另一个无线网在几分钟后断网（LEDE17.01.2)。

### ISSUE THREAD

**Issue by raykin** [aa65535/openwrt-dns-forwarder#17]
我使用小米的MINI路由器刷的17.01.2, 是用无线嫁接的方式联网的，我刷的英文版，连接的方式叫做 Join Network: Wireless Scan.
dns-forwarder是开启的，然后联网了大概十分钟左右就会断网。ping上一级的网关比如192.168.0.1是ping不通的. 
我需要在interfaces页面重连，但是只有十分钟不到的效果，又会断网。
杀掉dns-forwarder进程之后就没有这个问题。

这个问题又什么debug的方法吗？

**Comment by aa65535** [comment]
尝试监听到 127.0.0.1 和一个高位端口。
