### ISSUE TITLE
这个DNS Forwarder for openwrt能不能填多个dns 或者设置dns特殊端口

### ISSUE THREAD

**Issue by artcaster** [aa65535/openwrt-dns-forwarder#20]
这个DNS Forwarder for openwrt能不能填多个dns 或者设置dns特殊端口比如 option dns_servers '8.8.8.8; 8.8.4.4'
或者option dns_servers '208.67.222.222:443'

**Comment by aa65535** [comment]
不能多个，可以指定端口 https://github.com/aa65535/hev-dns-forwarder/pull/3

**Comment by artcaster** [comment]
谢谢 那为什么我填上option dns_servers '208.67.220.220:443' 却不能用呢

发自我的 iPad

**Comment by aa65535** [comment]
需要是支持TCP查询的DNS服务器。

2017年10月26日 15:38，artcaster <notifications@github.com>写道：
谢谢 那为什么我填上option dns_servers '208.67.220.220:443' 却不能用呢

发自我的 iPad

**Comment by artcaster** [comment]
我这运营商现在chinadns用压缩指针会被干扰，用chinadns+dns-forwarder会被tcp-restart，都已经不能解决dns干扰问题了，目前用的是国内某无污染dns，但cdn容易出错，也担心哪天就被封了，能否开发chinadns新版，比如基于gfwlist而不是chinadns_chnroute.txt 凡是在gfwlist列表里的域名就走国外并自动丢弃gfw返回的第一个数据包，这样系统开销和延时会低很多，不知道大大能不能做出来
