### ISSUE TITLE
dns-forwarder 找不到？

### ISSUE THREAD

**Issue by more-dopamine** [aa65535/openwrt-dns-forwarder#22]
LUCI里面显示dns-forwarder未运行，请问是什么原因？
Proxmox 里面安装虚拟机软路由，固件版本KOOLSHARE OPENWRT。以前在路由器上同样的配置运行正常。
`
root@Openwrt_Koolshare:~# /usr/bin/dns-forwarder
-ash: /usr/bin/dns-forwarder: not found
root@Openwrt_Koolshare:~# ls -l /usr/bin/dns-forwarder
-rwxr-xr-x    1 root     root         21435 Jul 21  2017 /usr/bin/dns-forwarder*
`

**Comment by pexcn** [comment]
找找？
```bash
find / -name "*dns*forwarder*"
```

**Comment by aa65535** [comment]
这个一般就是因为安装的架构不对，或者架构对了，SDK使用的 libc 不同，软件源里提供的都是根据官方SDK编译的版本，所以不能用的话自己找SDK重新编译。
