### ISSUE TITLE
openwrt x86/64 最新版 dns-forwarder编译时会报错

### ISSUE THREAD

**Issue by vbzc** [aa65535/openwrt-dns-forwarder#27]
openwrt x86/64 最新版 dns-forwarder编译时会报错，用命令 git reset --hard 86e2e2da7866ea8657b13fee6d2fa633749e838 回退后，编译没有报错，完成了

**Comment by pexcn** [comment]
报错信息是什么？

**Comment by vbzc** [comment]
这是出错信息，我是新手只能粘贴出错信息给大神看了

rm -f /openwrt/build_dir/target-x86_64_musl/dns-forwarder/dns-forwarder-1.2.1-28
9e8c9c7167200668dff83b1e0cbce258665387/.built
touch /openwrt/build_dir/target-x86_64_musl/dns-forwarder/dns-forwarder-1.2.1-28
9e8c9c7167200668dff83b1e0cbce258665387/.built_check
CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-bu
t-set-variable -Wno-error=unused-result -ffile-prefix-map=/openwrt/build_dir/tar
get-x86_64_musl/dns-forwarder/dns-forwarder-1.2.1-289e8c9c7167200668dff83b1e0cbc
e258665387=dns-forwarder-1.2.1-289e8c9c7167200668dff83b1e0cbce258665387 -Wformat
 -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z
,relro  -I/openwrt/staging_dir/target-x86_64_musl/usr/include -I/openwrt/staging
_dir/target-x86_64_musl/include -I/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.
0_musl/usr/include -I/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/includ
e/fortify -I/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/include " CXXFL
AGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-s
et-variable -Wno-error=unused-result -ffile-prefix-map=/openwrt/build_dir/target
-x86_64_musl/dns-forwarder/dns-forwarder-1.2.1-289e8c9c7167200668dff83b1e0cbce25
8665387=dns-forwarder-1.2.1-289e8c9c7167200668dff83b1e0cbce258665387 -Wformat -W
error=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,re
lro  -I/openwrt/staging_dir/target-x86_64_musl/usr/include -I/openwrt/staging_di
r/target-x86_64_musl/include -I/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_m
usl/usr/include -I/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/include/f
ortify -I/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/include " LDFLAGS=
"-L/openwrt/staging_dir/target-x86_64_musl/usr/lib -L/openwrt/staging_dir/target
-x86_64_musl/lib -L/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/usr/lib
-L/openwrt/staging_dir/toolchain-x86_64_gcc-8.3.0_musl/lib -znow -zrelro " make
 -C /openwrt/build_dir/target-x86_64_musl/dns-forwarder/dns-forwarder-1.2.1-289e
8c9c7167200668dff83b1e0cbce258665387/. AR="x86_64-openwrt-linux-musl-gcc-ar" AS=
"x86_64-openwrt-linux-musl-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-
copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -ffile-prefix-
map=/openwrt/build_dir/target-x86_64_musl/dns-forwarder/dns-forwarder-1.2.1-289e
8c9c7167200668dff83b1e0cbce258665387=dns-forwarder-1.2.1-289e8c9c7167200668dff83
b1e0cbce258665387 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_
SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=x86_64-openwrt-linux-musl-ld NM="x86_64-ope
nwrt-linux-musl-gcc-nm" CC="x86_64-openwrt-linux-musl-gcc" GCC="x86_64-openwrt-l
inux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" RANLIB="x86_64-openwrt-linux-
musl-gcc-ranlib" STRIP=x86_64-openwrt-linux-musl-strip OBJCOPY=x86_64-openwrt-li
nux-musl-objcopy OBJDUMP=x86_64-openwrt-linux-musl-objdump SIZE=x86_64-openwrt-l
inux-musl-size CROSS="x86_64-openwrt-linux-musl-" ARCH="x86_64" ;
make[4]: Entering directory '/openwrt/build_dir/target-x86_64_musl/dns-forwarder
/dns-forwarder-1.2.1-289e8c9c7167200668dff83b1e0cbce258665387'
make[4]: *** No targets specified and no makefile found.  Stop.
make[4]: Leaving directory '/openwrt/build_dir/target-x86_64_musl/dns-forwarder/
dns-forwarder-1.2.1-289e8c9c7167200668dff83b1e0cbce258665387'
Makefile:55: recipe for target '/openwrt/build_dir/target-x86_64_musl/dns-forwar
der/dns-forwarder-1.2.1-289e8c9c7167200668dff83b1e0cbce258665387/.built' failed
make[3]: *** [/openwrt/build_dir/target-x86_64_musl/dns-forwarder/dns-forwarder-
1.2.1-289e8c9c7167200668dff83b1e0cbce258665387/.built] Error 2
make[3]: Leaving directory '/openwrt/package/zc/openwrt-dns-forwarder'
time: package/zc/openwrt-dns-forwarder/compile#0.51#0.95#1.56
package/Makefile:111: recipe for target 'package/zc/openwrt-dns-forwarder/compil
e' failed
make[2]: *** [package/zc/openwrt-dns-forwarder/compile] Error 2
make[2]: Leaving directory '/openwrt'
package/Makefile:107: recipe for target '/openwrt/staging_dir/target-x86_64_musl
/stamp/.package_compile' failed
make[1]: *** [/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Er
ror 2
make[1]: Leaving directory '/openwrt'
/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by pexcn** [comment]
是不是编译的命令搞错了？make package/openwrt-dns-forwarder/compile V=s

或者要先把 openwrt-dns-forwarder 移动到 package 下面

**Comment by vbzc** [comment]
我是编译整个openwrt rom 用的 make -j1 V=s 命令，老版本放在 package /zc 目录下 是可以正常编译了，最新的 就不行了，不知道为啥？

**Comment by aa65535** [comment]
@vbzc 把 dl 目录下的 dns-forwarder* 删除一下。

**Comment by vbzc** [comment]
@aa65535 确实删除后，重新编译就成功了，能否请大神讲解一下，来龙去脉呀！ 谢谢
