### ISSUE TITLE
/etc/init.d/dns-forwarder 脚本好像有问题 运行不了

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-dns-forwarder#3]
版本是dns-forwarder_1.0.1-1_ramips_24kec.ipk 
/etc/init.d/dns-forwarder start 后ps并没有进程

执行/usr/bin/dns-forwarder -p 5300 -s 8.8.4.4 会运行并正常工作

**Comment by aa65535** [comment]
看一下设置的端口有没有被其他程序占用，因为 dns-forwarder 在端口被占用时没有错误提示。

**Comment by hdstar2009** [comment]
netstat -anp |grep 5300
并没有被占用。手工执行命令行是可以运行的。

然后我自己写了个脚本/etc/init.d/dns-forwarder，如下，也就正常运行了。有点奇怪，还是反馈下吧。

#!/bin/sh /etc/rc.common

START=75

start()
{
    /usr/bin/dns-forwarder -p 5300 -s 8.8.4.4 &
}

stop()
{
    service_stop /usr/bin/dns-forwarder
}

**Comment by aa65535** [comment]
更新到最新版本试试

**Comment by hdstar2009** [comment]
装了最新版，我看了下启动脚本，内容如下。5353不是chinadns的端口吗，现在也是chinadns占用。
/etc/init.d/dns-forwarder start 同样启动不了。

start_instance() {
    local enable
    local listen_addr
    local listen_port
    local dns_servers
    config_get_bool enable $1 'enable'
    [ "$enable" = 1 ] || return 0
    config_get listen_addr $1 'listen_addr'
    config_get listen_port $1 'listen_port'
    config_get dns_servers $1 'dns_servers'
    service_start /usr/bin/dns-forwarder \
        -b "${listen_addr:-0.0.0.0}" \
        -p "${listen_port:-5353}" \
        -s "${dns_servers:-8.8.8.8}"
}

start() {
    config_load 'dns-forwarder'
    config_foreach start_instance 'dns-forwarder'
}

stop() {
    service_stop /usr/bin/dns-forwarder
}

只要改成下面这样就可以正常运行：
start() {
        service_start /usr/bin/dns-forwarder -p 5300 -s 8.8.8.8
}

stop() {
        service_stop /usr/bin/dns-forwarder
}

**Comment by aa65535** [comment]
@hdstar2009 
5353是端口默认值，如果有设置端口的话是按照设置值的。

我这无法复现你的问题，提供一下 openwrt 的版本，感觉是 service_start 的问题。

**Comment by aa65535** [comment]
在 `SERVICE_DAEMONIZE=1` 下面加上一行 `SERVICE_DEBUG=1`, 然后执行 `/etc/init.d/dns-forwarder start` 查看打印的内容。

**Comment by hdstar2009** [comment]
用的是潘多拉的固件，Powered by LuCI Trunk (0.12+svn-r1024) / PandoraBox R2 14.09，BB的内核，可能确实是因为系统的问题。加上SERVICE_DAEMONIZE=1后执行脚本没任何输出。

不过有一点我再说下，dns-forwarder的默认端口不是5300吗（你上个版本和wiki说的是5300），同时chinadns的默认端口不是5353吗，你现在的dns-forwarder脚本写成5353是否疏忽弄错了？

至于脚本不能运行的问题，暂时忽略吧，反正我现在有替代方法。另外，chinadns和shadowsocks和shadowvpn都是用的你的版本，都没出现这个问题。

**Comment by aa65535** [comment]
@hdstar2009 
这里的 5353 可以认为是 typo, 不过 Wiki 里的默认值指的是 `/etc/config/dns-forwarder` 中 `listen_port` 的值。
BTW:  `/etc/config/dns-forwarder` 里 enable 是 1 吗？也就是启用了。

**Comment by hdstar2009** [comment]
@aa65535 

/etc/config/dns-forwarder 里 enable=0 改=1后 脚本可以运行了。
但是这个文件我没手工改动过，安装后默认应该就是0
问题应该就是这个了。我看了两个版本的ipk文件，里面的config配置文件默认就是enable=0

**Comment by aa65535** [comment]
@hdstar2009 默认是不启用的，你需要在 Luci 设置里面启用才行。

**Comment by hdstar2009** [comment]
@aa65535 
是我的问题，我只看到wiki那个说明，我以为这个ipk是没有luci配置的，我刚刚才发现原来在服务下面有dns转发的界面。
