### ISSUE TITLE
[需求]本地监听TCP协议

### ISSUE THREAD

**Issue by shNanChen** [aa65535/openwrt-dns-forwarder#30]
### 本地只有UDP协议
> root@openwrt:/etc/dnsmasq.d# netstat -nalp |grep dns-forwarder
udp        0      0 192.168.1.21:5300    0.0.0.0:*                           1417/dns-forwarder

### 同时监听TCP协议
dns-forwarder 本身作用是把 UDP DNS 查询转到远程 TCP DNS 查询，
作用就是个 DNS 代理，并且没有缓存，
那 TCP DNS 查询转到远程 TCP DNS 查询，也只是个代理作用

### 使用环境
为解决 DNS 污染，我是用 Dnsmasq + dns-forwarder，
通过 dnsmasq 配置文件配置 gfwlist 域名由 dns-forwarder 转发
`server=/google.com/192.168.1.1#5300`
这样配置在内网使用完全正常，非常顺滑

### 需求产生的原因
Shadowsocks Android 客户端有个 `Remote DNS` 配置，
长期以来都不能使用我上面配置的 DNS 服务，困扰了好久
抓包发现 dnsmasq 一直返回 `REFUSED`
测试发现在 dnsmasq 本机上 tcp 查询同样 `REFUSED`
```
# dig google.com @127.0.0.1 +tcp
; <<>> DiG 9.14.12 <<>> google.com @127.0.0.1 +tcp
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 22792
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; Query time: 31 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Aug 28 14:31:49 CST 2020
;; MSG SIZE  rcvd: 39
```

因该是这样，dnsmasq 的 `server=/google.com/192.168.1.1#5300` 配置，
会让 dnsmasq 收到 TCP 查询时，同样以 TCP 请求转发到上游，
因为上游 dns-forwarder 不支持 TCP，然后就没有然后了，解析失败

### 就是这样
自定义  `Remote DNS` 也是想对国内 CDN 更友好1点；
查了 dnsmasq 的手册，没有 TCP UDP 转换的选项；
也就想到了这里，啰里啰唆一堆，也不知道说清楚没，浪费各位时间了。

**Comment by aa65535** [comment]
一般都不会去监听 TCP 端口的，这种情况可以使用 iptables 解决：
假设 dns-forwarder 监听 5053 端口，dnsmasq 设置上游 DNS 服务器为 `8.8.8.8#53`，使用下面的规则即可。

`iptables -t nat -I OUTPUT 1 -p udp -d 8.8.8.8 --dport 53 -j DNAT --to 127.0.0.1:5053`

将发往 `8.8.8.8:53` 的 UDP 包转发到 `127.0.0.1:5053`(dns-forwarder) 处理。

dnsmasq 的 TCP 查询走正常的路径，不由 dns-forwarder 处理。

**Comment by shNanChen** [comment]
> dnsmasq 设置上游 DNS 服务器为 8.8.8.8#53

上游服务器设置8.8.8.8，这样对国内域名不友好呀，
我的上游服务器设置的是接入ISP的DNS

配置被墙域名才转发到 `dns-forwarder`，就发生我这样的情况

**Comment by aa65535** [comment]
没有让你全部使用 `8.8.8.8#53` 作为 dnsmasq 上游，你既然用了 gfwlist 那就肯定是有区分的。

其实就是将 dnsmasq 上游中的 dns-forwarder 部分，替换成 dns-forwarder 的上游。

假设 dns-forwarder 监听 5053 端口、上游设置是是 `8.8.8.8`，那就把 dnsmasq 上游中的 `127.0.0.1:5053` 替换成 `8.8.8.8#53` 。

**Comment by shNanChen** [comment]
哦~~~明白了，非常感谢

**Comment by shNanChen** [comment]
我再来填个 dnsmasq 有关 TCP 查询的坑。
PPPoe 拨号上网默认情况下，dnsmasq 会读取 `/tmp/resolv.conf.auto`文件来获取ISP下发的DNS服务器，
然后你用`dig baidu.com +tcp`来TCP查询，dnsmasq不会转发至上游DNS服务器，也不报错，最后返回是查询超时。
调试排错的时间，dnsmasq 有cache，udp正常查询后会被缓存，再TCP查询相同域名就会命中，看起来能正常返回。

调整配置文件，禁用resolv文件，改用server来指定上游DNS就可以了，dnsmasq 会正常转发内部tcp查询到上游DNS，当然也是以TCP查询的方式转发。
```
no-resolv
server=114.114.114.114
server=223.5.5.5
```
