### ISSUE TITLE
dns-forwarder是走tcp的吗？

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-dns-forwarder#4]
看wiki介绍说是走tcp，但是我查看端口发现是只占用了udp端口

[root@PandoraBox_M1:/root]#netstat -anp |grep dns-forwarder
udp        0      0 0.0.0.0:5300            0.0.0.0:\*                           5213/dns-forwarder

**Comment by hdstar2009** [comment]
设置说明

DNS-Forwarder 保持默认设置即可, 默认监听 5300 端口，如果有其它应用程序占用, 可以修改为其它可用端口. 上游 DNS 需要是国外的 DNS 服务器, 并且支持 TCP 查询

如果没有tcp查询的功能，那么和chinadns里面的上游服务器设置为8.8.8.8没有区别了吧

**Comment by aa65535** [comment]
向上游 DNS 查询时使用的是 TCP。
0.0.0.0:5300 是内网的监听端口当然是 UDP了，不然怎么接受 DNS 查询。

DNS-Forwarder 的作用就是将下游的 UDP 协议的 DNS 查询转换成 TCP 协议的 DNS 查询后发送到上游服务器。
