### ISSUE TITLE
新版不能从网页配置了么

### ISSUE THREAD

**Issue by ghost** [aa65535/openwrt-dns-forwarder#5]
![qq 20160913162042](https://cloud.githubusercontent.com/assets/10336224/18466403/277b6a0e-79ce-11e6-9982-8fc5aae01a25.png)

**Comment by ghost** [comment]
![qq 20160913162218](https://cloud.githubusercontent.com/assets/10336224/18466430/45551962-79ce-11e6-89fd-25774c51b6d1.png)

**Comment by aa65535** [comment]
LuCI 分离出去了 https://github.com/aa65535/openwrt-dist-luci

**Comment by ghost** [comment]
@aa65535 喔喔，没注意看，谢谢
