### ISSUE TITLE
请问可以提供下BCM53xx的IPK么

### ISSUE THREAD

**Issue by reusu** [aa65535/openwrt-dns-forwarder#6]
用SDK编译一直卡在zlib出错……

**Comment by aa65535** [comment]
https://wiki.openwrt.org/doc/howto/buildroot.exigence

**Comment by reusu** [comment]
感谢 DNS-Forwarder是编出来了 SS-libev一直提示“configure: error: mbed TLS libraries not found”

**Comment by aa65535** [comment]
@reusu 有安装 libmbedtls ？
http://openwrt-dist.sourceforge.net/dist/base/

**Comment by reusu** [comment]
@aa65535 非常感谢！！！
