### ISSUE TITLE
strange high load and fail to forward

### ISSUE THREAD

**Issue by GhostFlying** [aa65535/openwrt-dns-forwarder#8]
I used this app to forward dns some days and it always works well.

But today I found it failed to work and all dns queries sent to it by dig fail.

By some experiments, I find these  threads.
1. after one dns query sent, the dns-forward process will have a high load as 25% and not recover unless restart;
2. the shadowsocks server side do not receive any connection from the router, in other words, it do not forward dns query at all.

**Comment by aa65535** [comment]
restart.
