### ISSUE TITLE
谷歌8,.8.4.4ping不通，设置为dns-forwarder的上游dns能正常使用吗

### ISSUE THREAD

**Issue by hdstar2009** [aa65535/openwrt-dns-forwarder#9]
这两天很多地方谷歌dns都ping不通。
8.8.8.8以前就是大量丢包，8.8.4.4以前能ping通所以之前的dns-forwarder软件设置上游是8.8.4.4

这两天8.8.4.4完全ping不通了，但是发现还是能访问国外网站，这是什么原因？
ping不通的话就算开了ss，仍然会有解析请求成功发到8.8.4.4并获得结果吗？

**Comment by aa65535** [comment]
这个是TCP协议，与ping使用的协议不同。
